version: "3"

services:
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log/:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

