version: '3'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.3-fpm-alpine
    container_name: wordpress
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $DB_USER_NAME
      WORDPRESS_DB_PASSWORD: $DB_USER_PASSWORD
      WORDPRESS_DB_NAME: $DB_DBNAME
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
    restart: unless-stopped
  db:

    image: mysql:8.0
    container_name: db
    env_file: .env
    environment:
      MYSQL_DATABASE: $DB_DBNAME
      MYSQL_USER: $DB_USER_NAME
      MYSQL_PASSWORD: $DB_USER_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  webserver:
    depends_on:
      - wordpress
    image: nginx:stable-alpine3.17-slim
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certs:/opt/certs
    networks:
      - app-network

volumes:
  wordpress:
  db:

networks:
  app-network:
    driver: bridge